### ISSUE TITLE
Function within the template literal

### ISSUE THREAD

**Issue by puradox** [fleischie/vim-styled-components#12]
I don't believe the syntax is being highlighted correctly when functions are introduced to the template literal.
Especially the last curly brace on Line 6 in the screenshot below. It sticks out like a sore thumb to me.

![func](https://cloud.githubusercontent.com/assets/941763/23236310/957b3c82-f90d-11e6-8e9d-c021a8df1fba.png)

**Comment by fleischie** [comment]
Yes, this is especially annoying on such cases as:
```javascript
  const customColor = '#123456';

  const Header = styled.h2`
    border: ${props => props.highlight ? 'none' : `1px solid ${customColor}`};
  `;
```

I don't have a screenshot handy, but the outermost `}` get's highlighted as unclosed bracket. I suggest I investigate, whether a SCSS plugin or it's algorithm might fix this issue.
