### ISSUE TITLE
Think the `css` function's template strings aren't considered for styling

### ISSUE THREAD

**Issue by JikkuJose** [fleischie/vim-styled-components#14]
Edit (by fleischie):

Hey fleischie, thanks for your hard work! :100: 

I found an issue regarding the highlighting of specific keywords of the `styled-components` module. See the attached screenshot: The `css` tagged template literal leads to an inconsistently highlighted content.

I would appreciate some pointers or any hints on how to fix/bypass this. :bowing_man: 

Original description:
![screen shot 2017-03-20 at 11 03 17 am](https://cloud.githubusercontent.com/assets/227739/24089457/dfef4c46-0d5c-11e7-9160-c8ed73a9c027.png)

**Comment by fleischie** [comment]
Sorry @JikkuJose I cannot reproduce the above behavior.

Maybe you can provide some more information on what your working environment is: OS, vim-flavor, etc.

Also does `pad` and/or `shadow` contain semi-colons? Because I might suspect the missing `;` to cause problems later on. (Although only when not after a `}`...) I might consider looking into it, when I have time to fix the overall styling issues in #3 , #9 and #13 .

**Comment by JikkuJose** [comment]
#### Environment info:
- OSX 10.11.6
- Neovim 0.1.4

#### Vimrc
[.vimrc][vimrc] (shared for Neovim too)

#### Source
[Styles.js][styles]

[styles]: https://hastebin.com/jedebiferu.bash
[vimrc]: https://github.com/JikkuJose/dotfiles/blob/master/vimrc

**Comment by fleischie** [comment]
Do you use the latest version of this plugin? I cannot reproduce the issue you are describing above with my develop version (which is also the current master).

Technically, I don't include anything specific in the namespace to handle as styled-component's tagged template literals. I just check, whether `styled-components` is in the file and handle every template string as a container for css-syntax.

I furthermore cannot determine, whether there is a incompatability with another vim plugin you're using. If you can poke around some more and check, when and where exactly it breaks. I can better check, whether there is something I can do.

**Comment by fleischie** [comment]
Closing, because:

1. Inactivity, and
2. cannot reproduce.
