### ISSUE TITLE
Supply CSS3 rules

### ISSUE THREAD

**Issue by fleischie** [fleischie/vim-styled-components#9]
It seems the css syntax filed bundled with vim does not support CSS3 definitions, see [this test file](https://github.com/fleischie/vim-styled-components/blob/79d03643e400aaa7c200702449f56abb8051e717/test/typescript.ts#L30) in your styled-components powered vim.

There might be two options:
1. Depend on an already existing vim-plugin, that supplies these rules or
2. Manually define these rules inside this project.

I might have to contemplate a little about this. If you have any suggestions, opinions, etc. feel free to share them. :smiley:

**Comment by ismay** [comment]
I don't know how easy solution number 1 is compared to the other, but if 1 is feasible I'd choose that route. Less maintenance and duplication of work that way. Also, this issue is probably why I'm having this syntax highlighting bug:

<img width="292" alt="screen shot 2017-02-13 at 14 59 32" src="https://cloud.githubusercontent.com/assets/7355199/22886261/587a78be-f1fd-11e6-9f32-206dad9258b5.png">

**Comment by fleischie** [comment]
@ismay I don't know stylelint to be perfectly honest, but it seems it does construct an AST of the given file and check it against a given number of arguments/config-items/etc. As this project is merely a vim-plugin I don't have access to higher-order functionality. Or did I misunderstand you in this regard?

I checked for the css3 vim-plugin but it seems the ones I found didn't populate the syntax-pool to use in the styled-components one. Or I just didn't understand, why it didn't work, yet.

So my verdict in this particular case: I cannot find a way to enhance the standard CSS rules from vim with plugged in CSS rules (extending the official ones) and also using them in the `jsTemplateString` region. Although: I appreciate some more input on this matter, so if you (dear reader) have helpful insight in this matter, I am more than glad for your suggestions. :slightly_smiling_face:

**Comment by ismay** [comment]
> Or did I misunderstand you in this regard?

Probably not, I'm not at all experienced with creating vim plugins, so I have no idea what the best course of action would be here.

**Comment by fleischie** [comment]
After fiddling around with `vim-css3-syntax` I found some quirks I couldn't resolve just yet.

- `runtime! syntax/css/*.vim` loads all syntax files into the current buffer, but I think this and `syntax include syntax/css.vim` collide in some way or another, because depending on order of execution some definitions get loaded and some don't.
- for whatever reason `padding` and `color` don't get highlighted correctly as props, but as attrs.

I think I need some more time, fiddling around with both the included and the external css definitions.
